agsh/onvif

lib/cam.js
lib/imaging.js

Hello, I'm add getImagingSettings function ,  http://www.onvif.org/onvif/ver20/imaging/wsdl/imaging.wsdl#op.GetImagingSettings
It can use like your other media function, and it can use on my IPCam.

Add getImagingSettings function

---

lib/cam.js
lib/media.js

Connection reset (refused) handling.
Usually happens when IP address:Port or firmware error

Bugfix/check for SetSystemDateAndTime's optional value

---

lib/discovery.js

Changed the probe XML to discover more cameras in the network, probably newer ones

xml change to discover more cameras

---

example2.js

This test program carries out a brute force search of a network range looking for ONVIF devices. The IP range to scan, the ports to scan and the username/password are hard coded in the program.
The results of the search are displayed on the console

Test program to scan network looking for ONVIF devices

---

README.md
example3.js

Adds example3.js and updates the Readme file
Reads the cursor keys from the node command line and sends PTZ commands as a quick demo

Add PTZ example that reads the Cursor Keys on the command line

---

lib/cam.js

Fixed GetHostname and GetScopes

Fix invalid XML from bug report by Matthew Lien (Blue T)

---

example3.js

Also handle the keyboard auto-repeat

Re-write to use aTimer and Callbacks to schedule Stop Commands and add Goto Presets

---

lib/cam.js
lib/ptz.js

对于中文来说，这里的长度应该选取UTF8的长度而不是String的长度。否则会引发错误

Request Head Length Error

---

lib/media.js
test/media.coffee
test/serverMockup/media.GetAudioEncoderConfiguration.xml
test/serverMockup/media.GetAudioEncoderConfigurationOptions.xml
test/serverMockup/media.SetAudioEncoderConfiguration.xml

This pull request contains methods for audio-encoder configuration such as:
- setAudioEncoderConfiguration
- getAudioEncoderConfiguration
- getAudioEncoderConfigurationOptions

Audio encoder options

---

lib/discovery.js

#63 Bug in parsing XAddrs in Discovery

---

lib/cam.js

Indicates any warning while the cam is connecting. Links to #119

#119 Warning event

---

example2.js
example6.js
lib/cam.js

Fixes Issue Report #116 reported by @haraldrudell

Prevent error callback being called twice and fix request timeout on Mac

---

lib/device.js

Added some network related ONVIF requests.
Fixed JSDoc.

Added network related requests

---

lib/media.js
test/media.coffee
test/serverMockup/media.GetServiceCapabilities.xml

Add new request GetServiceCapabilities for media service.

---

README.md
example3.js
example6.js
lib/cam.js
lib/device.js
lib/media.js
test/common.coffee
test/ptz.coffee

Found using `codespell -wi3 **/*`.

Fix several typos

---

lib/cam.js
lib/events.js

Hi! I remembered a conversation that was in May ( sometimes I do it ;) ): https://github.com/agsh/onvif/pull/137 https://github.com/agsh/onvif/pull/161
And finally remove `eventEmitter` property and made right inheritance from `EventEmitter`
Since I have not had a camera for testing for two years, please check the code and maybe test it on the device.

Make Cam works properly like EventEmitter inheritor

---

lib/media.js
test/common.coffee

The response should be a list of video sources.
**This breaks backward compatibility!**

Fix getVideoSources response

---

lib/cam.js
test/common.coffee

If GetServices does not work fail back to GetCapabilities.
If `GetServices` works, `capabitilies` is not created as the response of `GetServices` is too different from `GetCapabilities`.
`uri` is also created using the response of `GetServices`.

Connect using GetServices.

---

README.md

This fixes the broken ONVIF image URL in README.md

Update ONVIF image URL

---

lib/discovery.js

Resolve issue #198 
Hi @agsh.
Can i solve problem a this way. Just adding listeningPort option to the function

add option in probe function that allow set specific listen port

---

lib/recording.js

#223 
Add more function include:
- GetRecordingJobs
- CreateRecordingJob
- DeleteRecordingJob
- GetRecordingSummary (recording search)
- GetRecordingInformation (recording search)
- GetRecordingConfiguration
- GetRecordingJobState
- DeleteRecordingJob
- GetRecordingOptions
- GetServiceCapabilities (recording control)
- GetTrackConfiguration
- GetRecordingJobConfiguration
- SetRecordingJobMode

Add more function to Recording service

---

.eslintrc.js
IMPLEMENTED.md
legacyTest/common.js
src/legacy/cam.ts
src/media.ts

Add `getActiveSources`, `getSnapshotUri`, `getStreamUri` methods

---

package-lock.json

Result of running `npm audit fix` to resolve a security finding in mocha. 
result of a local npm test run (summary)
```
150 passing (16s)
```

GHSA-f8q6-p94x-37v3 (mocha update)

---

README.md
lib/media.js

implemented custom OSD position by adding extra field in line 1267

[feat] implemented custom OSD position

---

lib/media.js

Revert "[feat] implemented custom OSD position"

---

lib/media.js

[feat] custom OSD position
[fix] typo in setOSD: videoSourceConfigurationToken
@agsh I fixed all the problems, really sorry for inconvience, this is my first time opening a PR, not really experienced. I tested the code using ```npm run lint``` and everything seemed to be fine.

[feat] custom OSD position

---

README.md

Hello @RogerHardiman!
I think that in your last PR into `master` we are intersecting:
https://github.com/agsh/onvif/blob/master/README.md#troubleshooting
https://github.com/agsh/onvif/blob/master/README.md#testing
So, maybe remove the naming `testing` to `troublebleshooting` and remove my section at all?

fix: readme fixes

---

lib/imaging.js

Hi Sir,
The GetStatus API is implemented and fixed a wrong xmlns type of Move API.
Please feel free to contact me if you have any questions. 
Thank you.
Best Regards,
Walker

Add GetStatus for Imaging

---

lib/imaging.js

Hi Sir,
In this change, we added irCutFilter control in Imaging Settings API.
Thanks,
Best Regards,
Walker

Add irCutFilter control in Imaging Settings

---

lib/events.js

I tried your branch and it didn't reconnect after restarting my doorbell.
I have added some more error codes to retry on which I found when playing round turning off wifi on my laptop and disconnecting the doorbell from my network.
I have also changed the logic so it has a maximum delay rather than resetting back to 10ms as I think this is more standard in backoff type logic.

retry on other error codes and sets max retry delay
