agsh/onvif

lib/cam.js
The authentication fail with my TRENDNET cameras. 
With the help of wireshark, i discover a BASIC Authorization in the POST request not compatible, i guess, with the  SOAP Security processus.
If i remove "reqOptions.auth = this.username + ':' + this.password;", the authentication success.
=> Remove BASIC authentication from POST request

lib/cam.js
preventing node app crash on socket connection error or wrong IP address
crash: [TypeError: Cannot read property 'device' of undefined]
=> preventing node app crash on socket connection error

lib/cam.js, test/common.coffee
Note that using 10.255.255.1 in the test is due to the fact that this is a non-routable address and will always time out.
=> Adds an optional connect timeout method. Fixes #27

lib/utils.js
This commit improves parsing of SOAP replies with XMLNS name space attributes in the tag.
When an XMLNS is present (as they are with the SOAP replies from the RPOS ONVIF NVT) they cause the data structure created by XML2JS to be generated differently.
This in turn causes problems trying to extract values from the ONVIF SOAP replies (like the RTSP URI).
The best fix would be to change xml2js to tell it to ignore xmlns attributes (but keep other attributes) but the simple fix is to filter the SOAP XML before passing it to xml2js
=> Improve SOAP parsing

lib/media.js
TTL and port can now be 0 and autoStart can now be false, which are all valid values.
=> allow valid multicast parameter values

lib/cam.js
This change allows connecting to a NVT with an empty username and empty password.
Was testing with an ONVIF NVT which was set to no authentication. However this NVT complained when WS-Security (with empty username/password) was sent.
The empty username and password check is removed and WS-Security is only used when there is a username and password
=> Allow empty username and password

lib/discovery.js, test/discovery.coffee, test/serverMockup.coffee
Allows to specify an optional device name such as `eth0`
=> Fixed #55: Discovery with multiple network interfaces

lib/cam.js
Added compatibility methods:
-GetNetworkInterfaces
http://www.onvif.org/ver10/device/wsdl/GetNetworkInterfaces
-GetNetworkProtocols
http://www.onvif.org/ver10/device/wsdl/GetNetworkProtocols
These methods add very usefull information about network interface of the device such as MAC address, IP version, configured protocol...
=> Implementation network interfaces method

example5.js, lib/cam.js
HTTP agents are useful, specially if you need to connect to your cameras through SSH. Instead of forwarding a bunch of ports you just open a secure SOCKS proxy :)
Also added examples5.json which connects through proxy to the camera
=> added support for HTTP agents (socks5, etc)

lib/cam.js
Cath exceptions if a non onvif device responds to a discovery with a wrong soap message
=> Add a try catch to getSystemDateAndTime function

lib/cam.js, lib/discovery.js
URN property was only used to deduplicate discovered devices (using `probe()`).
Now it also populates a field on the Cam camera. 
When using Cam instances, this field can be used as a stable id (as opposed to IP address for instance)
=> Discovery now populates `urn` property of Cam instance

example6.js, lib/cam.js, lib/events.js, package.json, startServerMockup.js, test/discovery.coffee, test/events.coffee, test/serverMockup.coffee, test/serverMockup/GetCapabilities.xml, test/serverMockup/Probe.xml, test/serverMockup/Unsubscribe.xml, test/serverMockup/device.GetNetworkInterfaces.xml, test/serverMockup/device.GetZeroConfiguration.xml, test/zzzterminate.coffee
Events.....    Changes to make events work with Axis cameras and with NAT.
There is a new file called example6.js which I am using to connect to 4 different cameras and to the serverMockup and can receive events from all of them.
The Axis events are not documented properly in the ONVIF Spec and I had to use ODM and Wireshark. They need to include a <To> tag and a <SubscriptionId> tag in the Pull Request.
ServerMockup.... made changes so discovery works properly and ODM now detects it. Added a few other XML stubs. The purpose was to get ODM to receive events from the ServerMockup so I could verify how ODM received events.
=> Improve Events and ServerMockup

lib/utils.js
Permit to remove xmlns in the Dialect of a PullMessagesResponse like the following:
```xml
<wsnt:Topic Dialect="http://www.onvif.org/ver10/tev/topicExpression/ConcreteSet xmlns:wsnt=http://docs.oasis-open.org/wsn/b-2 xmlns:tns1=http://www.onvif.org/ver10/topics xmlns:tnssamsung=http://www.samsungcctv.com/2011/event/topics">tns1:Device/tns1:Trigger/tnssamsung:DigitalInput</wsnt:Topic>
```
=> Issue #134 Improve xmlns parsing

lib/utils.js
On SOAP error, some cameras send a wrong SOAP structure (see Issue #73).
This PR permit to avoid having the error `"TypeError: Cannot read property '0' of undefined"`, but instead will try to read both `reason` and `detail` information, if one of them is wrong, we can still get the other.
=> Better SOAP error handling

lib/cam.js, lib/events.js, test/common.coffee
Using `util.inherits` makes `EventEmitter` global to all `Cam` objects.
It is recommended to `extend` instead of using `util.inherit`, which fixes the problem, but it is not possible as we don't use `class`es.
This pull request fixes that by instantiating an `EventEmitter` in the `Cam` constructor and creating `on` and `emit` functions.
I also added a condition on listeners in `_eventRequest` to avoid `_eventRequest`/`_eventPull`/`pullMessages` loop when we unsubscribe while waiting for a `pullMessages` response (which is almost always the case). The listeners are also removed in `unsubscribe` because we could never subscribe anymore as we create a PullPointSubscription only if there is no listeners.
The code below shows that the `EventEmitter` is global. Also include a `console.log` of …
=> Fix EventEmitter global to all Cam objects.

lib/cam.js
In some cases, a null pointer may be appear here.
=> Modify null pointer in Cam.js

lib/cam.js
Fixes #160, tested on real device that has this issue
=> Fix for cameras without UTCDateTime

lib/device.js
when only one network inteface is returned.
The returned object is now the Array of network interfaces (as declared in the JSDoc) instead of an object containing the array.
**This breaks backward compatibility!**
Also breaks the test I added in the PR #144, depending on which PR is accepted first, I will add commit on this PR or the other.
=> Fix getNetworkInterfaces response returning a non-array

example7.js, lib/cam.js, lib/media.js, lib/ptz.js, test/common.coffee, test/device.coffee
Hi @agsh  and @chriswiggins 
I've got some new ONVIF Cameras that use Profile T and H265.
I've added support and just wanted you to have a quick check before I merge to master.
The two important changes in ONVIF are
You must use GetServices() to get the XAddrs and not GetCapabilities. This lets us check if the Media XAddr is 'media10' or 'media20'  (Media Version 1.0 or Media Version 2.0).
The for GetProfiles() I have to use the old Media XML format and XML namespace or the new Media2 XML format and namespace. This lets me get a list of Profiles where the Encoder can be H265.
The reply for Media2 GetProfiles() is in a slightly different format (different XML tag names) but I modify the result so the reults are in the same format as the old media10 GetProfiles. This means the …
=> Review of Profile T and Media2 API changes requested

lib/cam.js, lib/events.js
Hi, first of all, thank you so much for this project, it has really saved me quite a bit of time, anyways first time contributing to an open source project, so if anything should be improved please let me know.
I found an issue when the camera receives requests via port forwarding, eg: requests to `external_ip:554`, get forwarded to the camera on the actual Onvif port 80, this will cause the camera to respond with port 80 for the address that is used for establishing a subscription, which in turn means no events will be received, below is a trivial workaround that from my experience works.
I wasn't sure how I could add a test case for this, so any pointers would be appreciated.
=> setting the port for pull messages to user-provided ports

README.md, lib/ptz.js
Hi.
Im not sure why there are differences between the code comments and the docs but shouldn't the docs be auto generated from the code comments to avoid this exact problem? 🤔
Thanks.
=> Fix documentation

IMPLEMENTED.md, legacyTest/common.js, src/device.ts, src/legacy/cam.ts, src/media.ts, src/onvif.ts, src/ptz.ts, src/test.ts, src/utils.ts
Add `getConfigurationOptions`, `getConfigurations`, `getNodes` `systemReboot` methods and make legacy version common tests compliant
=> Make legacy version common tests compliant

lib/cam.js, lib/discovery.js, lib/ptz.js, lib/utils.js
It looks like SOAP 1.2 requires ths field and 1 ONVIF camera requires it
The code is not very efficient. It parses the XML to be sent to generate
the action string. It would be better for action strings to be hard coded
throughout the library
=> Add action string to Content-Type in ONVIF HTTP Request Header, fixes for PTZSpaces and RelativePTZ

.github/workflows/pr.yml
This adds a GH workflow that would run the tests whenever a PR is opened to merge to the master branch. Checks compatibility with Node 14, 16, and 18.
=> GH test workflow for PRs

lib/imaging.js
This change follows Onvif ver20 imaging.wsdl to implement these Focus operations APIs in the imaging.js file:
1. GetMoveOptions
2. Move
3. Stop
Please feel free to contact me if you have any questions.
Thank you.
Best Regards,
Walker
=> Add support for focus control commands: GetMoveOptions, Move, Stop

lib/events.js
I see a crash when called unsubscribed without callback to prevent a crash I added a check
```
2023-10-20 11:04:50.893 - error: tapo.0 (681712) uncaught exception: callback.call is not a function
2023-10-20 11:04:50.894 - error: tapo.0 (681712) TypeError: callback.call is not a function
at Cam. (/opt/iobroker/node_modules/onvif/lib/events.js:309:14)
at parseSOAPString (/opt/iobroker/node_modules/onvif/lib/utils.js:108:3)
at IncomingMessage. (/opt/iobroker/node_modules/onvif/lib/cam.js:297:4)
at IncomingMessage.emit (node:events:526:35)
at IncomingMessage.emit (node:domain:489:12)
at endReadableNT (node:internal/streams/readable:1359:12)
at processTicksAndRejections (node:internal/process/task_queues:82:21)
```
=> Add callback call check

lib/events.js
TP-Link Tapo C220 (firmware 1.1.6) supports ONVIF pull-point subscriptions but unfortunately sets the socket read timeout on the pull endpoint to 10 seconds - i.e. every _pull messages_ request gets closed by the cam after 10 seconds of I/O inactivity.
I tried changing various timeouts on the network & messages level and using TCP keep-alives to no avail - the cam sends TCP FIN packet roughly 10 seconds after receiving HTTP request headers and the connection gets closed prematurely with `ECONNRESET` error.
This pull request intercepts `ECONNRESET` error before it is propagated to event callbacks and restarts the event request loop (which handles subscription expiration, renewal, etc).
I believe the original plan of the author was to handle such cases one level higher - in `_eventPull()` - …
=> Restart event loop for pull messages request when cam drops connection

lib/cam.js, lib/events.js
Hi, I am running https://shinobi.video/ which uses this library and have noticed that sometimes the ONVIF events don't get triggered. I narrowed this down to when there is a connection disruption e.g. my router updates or the camera is restarted.
This Pull Requests adds a retry mechanism if the connection fails. I have added a configurable wait time and used that as a kind of feature flag so this change is more backwards compatible.
I struggled to write tests for this due to the timeout and I think the mock server being in an external process. If someone could guide me the best way to test this I would be happy to write some tests.
I have tested this locally adding a listener, restarting my camera and then seeing if events continue to flow
=> adds retry when pull subscriptions fails

lib/media.js
Adding ability to set OSD of type DateAndTime.
The function setOSD from lib/media.js previously only supported the addition of Plain Text, as indicated in the comment at line 1286: "ONVIF can handle custom positions, date/time, text, font sizes, transparency, images, etc. **We only support Plain Text**."
As part of my work, I encountered the need to configure the OSD of date and time for certain cameras. Upon reviewing the Onvif MediaBinding specifications available at https://www.onvif.org/ver10/media/wsdl/media.wsdl and https://www.onvif.org/ver20/media/wsdl/media.wsdl (both media and media2 versions), I found that in the setOSD function, it is possible to set the Type as DateAndTime for configuring date and time display.
Furthermore, I examined the output of the getOSDs function for my …
=> feat: setOSD support DateAndTime

lib/device.js
SetNTP is not working with DNS due to a missing schema version URL
Result bad Request 400 
I added  xmlns="http://www.onvif.org/ver10/schema" to DNSname tag
=> SetNTP is not working with DNS due to a missing schema version URL

lib/media.js
Added Media2 support for the following functions:
GetVideoEncoderConfigurations and GetVideoEncoderConfigurationOptions
SetVideoEncoderConfiguration
With these updates, we now support setting the H.265 encoder and configuring constant bit rate.
Sources:
[ONVIF Media2 WSDL](https://www.onvif.org/ver20/media/wsdl/media.wsdl)
Tested on Hanwha camera.
=> media2 support for videoencoders 

lib/ptz.js, test/ptz.js
get PTZ position  pan and til and zoom
=> get complete information about preset points
